pipeline {
	agent any

	tools {
		maven "MAVEN"
	}

	stages {
		stage('Initialize') {
			steps {
				echo "PATH = ${M2_HOME}/bin:${PATH}"
				echo "M2_HOME = /opt/apache-maven-3.9.0"
			}
		}
		stage('Build') {
			steps {
				dir("/var/lib/jenkins/workspace/Java_Pipeline_Job/my-app") {
					sh 'mvn -B -DskipTests clean package'
				}

			}
		}
		stage('Stage 2') {
			steps {
				sleep time: 60, unit: 'SECONDS' // introduce a 5-minute delay
				// do something in stage 2
			}
		}
		stage("Publish to Nexus Repository Manager") {
			steps {
				script {
                    def workspace = pwd()
                    echo "You are currently in $workspace"
					pom = readMavenPom file: "/var/lib/jenkins/workspace/Java_Pipeline_Job/my-app/pom.xml";
					filesByGlob = findFiles(glob: "var/lib/jenkins/workspace/Java_Pipeline_Job/my-app/target/**/*.${pom.packaging}")
                    echo "Files found: ${filesByGlob}"
					if (filesByGlob.length > 0) {
						def artifactPath = filesByGlob[0].path
						echo "* File: ${artifactPath}, group: ${pom.groupId}, packaging: ${pom.packaging}, version ${pom.version}"
						nexusArtifactUploader(
							nexusVersion: 'nexus3',
							protocol: 'http',
							nexusUrl: '13.59.139.160:8081/',
							groupId: pom.groupId,
							version: pom.version,
							repository: 'maven-java-pipeline-repository',
							credentialsId: 'NEXUS_CRED',
							artifacts: [
								[artifactId: pom.artifactId,
									classifier: '',
									file: artifactPath,
									type: pom.packaging
								],
								[artifactId: pom.artifactId,
									classifier: '',
									file: "${workspace}/pom.xml",
									type: 'pom'
								]
							]
						)
					} else {
						error "* No files found to upload"
					}
				}
			}
		}
    }
}