pipeline {
	agent any

	tools {
		maven "MAVEN"
	}

	stages {
		stage('Initialize') {
			steps {
				echo "PATH = ${M2_HOME}/bin:${PATH}"
				echo "M2_HOME = /opt/apache-maven-3.9.0"
			}
		}
		stage('Build') {
			steps {
				dir("/var/lib/jenkins/workspace/Java_Pipeline_Job/my-app") {
					sh 'mvn -B -DskipTests clean package'
				}

			}
		}
       stage("Build and analyze code") {
    steps {
        withSonarQubeEnv('SonarQube') {
            sh 'mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dmaven.test.failure.ignore=true'
        }
    }
}

stage("Wait for quality gate evaluation") {
    steps {
        timeout(time: 1, unit: 'HOURS') {
            script {
                def qg = waitForQualityGate()
                if (qg.status != 'OK') {
                    error "Pipeline aborted due to quality gate failure: ${qg.status}"
                }
            }
        }
    }
}
		stage("Publish to Nexus Repository Manager") {
			steps {
				script {
                    echo "$workspace"
					pom = readMavenPom file: "/var/lib/jenkins/workspace/Java_Pipeline_Job/my-app/pom.xml";
                    echo "$workspace"
                    sh "ls -la /var/lib/jenkins/workspace/Java_Pipeline_Job/my-app/target"
					filesByGlob = findFiles(glob: "target/*.${pom.packaging}");
					echo "Files found: ${filesByGlob}"
                    echo "${filesByGlob[0].name} ${filesByGlob[0].path} ${filesByGlob[0].directory} ${filesByGlob[0].length} ${filesByGlob[0].lastModified}"
					artifactPath = filesByGlob[0].path;
					artifactExists = fileExists artifactPath;
					if (artifactExists) {
						echo "* File: ${artifactPath}, group: ${pom.groupId}, packaging: ${pom.packaging}, version ${pom.version}";
						nexusArtifactUploader(
							nexusVersion: 'nexus3',
							protocol: 'http',
							nexusUrl: '18.188.169.30:8081/',
							groupId: 'pom.com.mycompany.app',
							version: 'pom.1.0-SNAPSHOT',
							repository: 'maven-java-pipeline-repository',
							credentialsId: 'NEXUS_CRED',
							artifacts: [
								[artifactId: 'pom.my-app',
									classifier: '',
									file: artifactPath,
									type: pom.packaging
								],
								[artifactId: 'pom.my-app',
									classifier: '',
									file: "pom.xml",
									type: "pom"
								]
							]
						);
					} else {
						error "* File: ${artifactPath}, could not be found";
					}
				}
			}
		}
	}
}